"""Oriented Bounding Box Annotations.

Provides a toolkit to work with oriented bounding box ann_info.

Author:
    Yvan Satyawan <y_satyawan@hotmail.com>

Created on:
    February 19, 2020
"""
import json
from time import time
from datetime import datetime
from typing import List

import numpy as np
import os.path as osp
from PIL import Image, ImageColor, ImageDraw, ImageFont
import colorcet as cc
import pandas as pd
from tqdm import tqdm
from .polyiou import iou_poly, VectorDouble


class OBBAnns:
    def __init__(self,
                 ann_file):
        """Toolkit to work with Oriented Bounding Boxes.

        Workflow is generally to initialize the class, load ann_info, run the
        training loop, then load proposals generated by the network, and finally
        to calculate the various metrics.

        Provides the following methods:
        - load_annotations(): Loads annotations to memory.
        - load_proposals(): Loads given proposals to memory.
        - set_annotation_set_filter(): Applies a filter by annotation set.
        - get_imgs(): Gets desired image information.
        - get_anns(): Gets annotation information for a given image.
        - get_cats(): Gets all cats in the dataset.
        - get_ann_ids(): Gets annotation information by annotation ID.
        - get_img_ann_pairs(): Gets image-annotation pairs by image.
        - get_img_props(): Gets proposasls that belong to a given image.
        - calculate_metrics(): Calculate validation metrics from proposals.
        - visualize_anns(): Visualizes annotations for an image using Pillow.

        :param ann_file: Path to the annotation file.
        :type ann_file: str
        """
        # Store class attributes
        self.ann_file = ann_file

        self.proposal_file = None
        self.proposals = None
        self.props_oriented = False
        self.prop_ann_set_idx = None
        self.dataset_info = None
        self.img_info = None
        self.img_idx_lookup = dict()
        self.annotation_sets = None
        self.cat_info = None
        self.ann_info = None
        self.chosen_ann_set = None  # type: None or List[str]
        self.classes_blacklist = []
        self.classes_blacklist_id = []

    def __repr__(self):
        information = "<Oriented Bounding Box Dataset>\n"
        information += f"Ann file: {self.ann_file}\n"
        if self.dataset_info is not None:
            information += f"Num images: {len(self.img_info)}\n"
            information += f"Num anns: {len(self.ann_info)}\n"
            information += f"Num cats: {len(self.cat_info)}"
        else:
            information += "Annotations not yet loaded\n"
        if self.proposal_file:
            information += f"\nProposal file: {self.proposal_file}"
            information += f"\nNum proposals: {len(self.proposals)}>"
        else:
            information += "No proposals loaded."
        return information

    def __len__(self):
        return 0 if self.img_info is None else len(self.img_info)

    @staticmethod
    def _xor_args(m, n):
        only_one_arg = ((m is not None and n is None)
                        or (m is None and n is not None))
        assert only_one_arg, 'Only one type of request can be done at a time'

    def load_annotations(self, annotation_set_filter=None):
        """Loads ann_info into memory.

        This is not done in the init in case a dataset is just to be initialized
        without actually loading it into memory yet.

        :param annotation_set_filter: Set a filter so that future calls to
            methods which get annotations only returns a specific annotation
            sets. If None is given, then the all annotation sets are returned.
            Annotation sets can also be chosen each time a method which gets
            annotations is called.
        :type annotation_set_filter: str
        """
        print('loading ann_info...')

        # Set up timer
        start_time = time()
        with open(self.ann_file, 'r') as ann_file:
            data = json.load(ann_file)

        self.dataset_info = data['info']
        self.annotation_sets = data['annotation_sets']

        # Sets annotation sets and makes sure it exists
        if annotation_set_filter is not None:
            assert annotation_set_filter in self.annotation_sets, \
                f"The chosen annotation_set_filter " \
                f"{annotation_set_filter} is not a in the available " \
                f"annotations sets."
            self.chosen_ann_set = annotation_set_filter
        else:
            self.chosen_ann_set = self.annotation_sets

        self.cat_info = {int(k): v for k, v in data['categories'].items()}

        # Process annnotations
        ann_id = []
        anns = {'a_bbox': [],
                'o_bbox': [],
                'cat_id': [],
                'area': [],
                'img_id': [],
                'comments': []}

        for k, v in data['annotations'].items():
            ann_id.append(int(k))
            anns['a_bbox'].append(v['a_bbox'])
            anns['o_bbox'].append(v['o_bbox'])
            anns['cat_id'].append(v['cat_id'])
            anns['area'].append(v['area'])
            anns['img_id'].append(v['img_id'])
            anns['comments'].append(v['comments'])
        self.ann_info = pd.DataFrame(anns, ann_id)

        self.img_info = data['images']

        for i, img in enumerate(data['images']):
            # lookup table used to figure out the index in self.img_info of
            # every image based on their img_id
            self.img_idx_lookup[int(img['id'])] = i

        self.img_info = data['images']

        print("done! t={:.2f}s".format(time() - start_time))

    def load_proposals(self, proposal_file):
        """Loads proposals into memory.

        This loads the generated proposals into memory so that metrics can be
        calculated on them.

        :param proposal_file: Path to the generated proposals file.
        :type proposal_file: str
        """
        assert self.img_info is not None, 'Annotations must be loaded before ' \
                                          'proposals'
        self.proposal_file = proposal_file
        print('loading proposals...')
        start_time = time()
        with open(proposal_file, 'r') as p_file:
            props = json.load(p_file)

        # Get the index of the proposed annotation set so the right cat is
        # chosen as the GT set.
        self.prop_ann_set_idx = self.annotation_sets.index(
            props['annotation_set']
        )
        props_dict = {
            'bbox': [],
            'cat_id': [],
            'img_idx': []
        }
        bbox_len = len(props['proposals'][0]['bbox'])
        assert bbox_len in (4, 8), 'bbox proposal is malformed. \'bbox\' ' \
                                   'must have a length of 4 or 8.'
        if bbox_len == 8:
            self.props_oriented = True

        for prop in props['proposals']:
            prop_img_idx = self.img_idx_lookup[prop["img_id"]]
            props_dict['bbox'].append(np.asarray(prop['bbox'],
                                                 dtype=np.float32))
            props_dict['cat_id'].append(prop['cat_id'])
            props_dict['img_idx'].append(prop_img_idx)

        self.proposals = pd.DataFrame(props_dict)

        print('done! t={:.2f}s'.format(time() - start_time))

    def set_annotation_set_filter(self, annotation_set_filter: List[str]):
        """Sets the annotation set filter for future get calls.

        :param annotation_set_filter: The annotation set to filter by.
        :type annotation_set_filter: str
        """
        self.chosen_ann_set = annotation_set_filter

    def set_class_blacklist(self, blacklist):
        """Sets the annotation set filter for future get calls.

        :param blacklist: a list of classnames to be ignored
        :type blacklist: list
        """
        self.classes_blacklist = blacklist
        self.classes_blacklist_id = [key
                                     for (key, value) in self.cat_info.items()
                                     if value['name'] in self.classes_blacklist]

    def get_imgs(self, idxs=None, ids=None):
        """Gets the information of imgs at the given indices/ids.

        This only works with either idxs or ids, i.e. cannot get both the given
        idxs AND the given ids.

        :param idxs: The indices of the desired images.
        :param ids: The ids of the desired images.
        :type idxs: list or tuple
        :type ids: list or tuple
        :returns: The information of the requested images as a list. Filenames
            will have had the data root as well as paths added to them.
        :rtype: list
        :raises: AssertionError if both idxs and ids are given.
        """
        self._xor_args(idxs, ids)

        if idxs is not None:
            assert isinstance(idxs, list), 'Given indices idxs must be a ' \
                                           'list or tuple'

            return [self.img_info[idx] for idx in idxs]
        else:
            assert isinstance(ids, list), 'Given ids must be a list or tuple'
            return [self.img_info[self.img_idx_lookup[i]] for i in ids]

    def get_anns(self, img_idx=None, img_id=None, ann_set_filter=None):
        """Gets the annotations for a given image by idx or img_id.

        :param img_idx: The index of the image.
        :param img_id: The img_id of the image.
        :param ann_set_filter: Filter by annotation set. If None, uses the
            filter chosen in the method set_annotation_filter().
        :type img_idx: int
        :type img_id: int
        :type ann_set_filter: str
        :returns: Annotation information (dict) for that image with the key
            being the annotation ID and the value being the annotation
            information.
        :rtype: pd.DataFrame
        """
        self._xor_args(img_idx, img_id)

        if img_idx is not None:
            return self.get_ann_ids(self.img_info[img_idx]['ann_ids'],
                                    ann_set_filter)
        else:
            ann_ids = self.img_info[self.img_idx_lookup[img_id]]['ann_ids']
            return self.get_ann_ids(ann_ids, ann_set_filter)

    def get_cats(self):
        """Just returns the self.cat_info dictionary.

        :returns The category information of the currently loaded dataset.
        :rtype: dict
        """
        return {key: value for (key, value) in self.cat_info.items()
                if value['annotation_set'] in self.chosen_ann_set
                and value['name'] not in self.classes_blacklist}

    def get_ann_ids(self, ann_ids, ann_set_filter=None):
        """Gets the annotation information for a given list of ann_ids.

        :param ann_ids: The annotation ids that are desired.
        :param ann_set_filter: Filter by annotation set. If None, uses the
            filter chosen in the method set_annotation_filter().
        :type ann_ids: list[str] or list[int]
        :type ann_set_filter: str
        :returns: The annotation information requested.
        :rtype: pd.DataFrame
        """
        assert isinstance(ann_ids, list), 'Given ann_ids must be a list or ' \
                                          'tuple'

        ann_ids = [int(i) for i in ann_ids]
        selected = self.ann_info.loc[ann_ids]

        # Get annotation set index and return only the specific category id
        if ann_set_filter is None:
            ann_set_filter = self.chosen_ann_set
        ann_set_idx = [self.annotation_sets.index(ann_set)
                       for ann_set in ann_set_filter]

        def filter_ids(record):
            return [int(record[idx])
                    for idx in ann_set_idx
                    if int(record[idx]) not in self.classes_blacklist_id]

        selected['cat_id'] = selected['cat_id'].map(filter_ids)
        selected = selected[selected['cat_id'].map(lambda x: len(x)) > 0]

        return selected

    def get_img_ann_pair(self, idxs=None, ids=None, ann_set_filter=None):
        """Gets the information and annotations at the given indices/ids.

        This only works with either idxs or ids, i.e. cannot get both the given
        idxs AND the given ids.

        :param idxs: The indices of the desired images.
        :param ids: The ids of the desired images.
        :param ann_set_filter: Filter by annotation set. If None, uses the
            filter chosen in the method set_annotation_filter().
        :type idxs: list or tuple
        :type ids: list or tuple
        :type ann_set_filter: list or str
        :returns: The information of the requested images as a tuple (list of
            image info, corresponding annotations)
        :rtype: tuple
        :raises: AssertionError if both idxs and ids are given.
        """
        self._xor_args(idxs, ids)

        imgs = self.get_imgs(idxs, ids)
        anns = [self.get_ann_ids(img['ann_ids'], ann_set_filter)
                for img in imgs]

        return imgs, anns

    def get_img_props(self, idxs=None, ids=None):
        """Gets the proposals of an image at a given index or with a given ID.

        :param idxs: The indices of the desired images.
        :param ids: The ids of the desired images
        :type idxs: list or tuple
        :type ids: list or tuple
        :returns: The information of the requested images as a tuple (list of
            image info, corresponding annotations)
        :rtype: pd.DataFrame
        :raises: AssertionError if both idxs and ids are given.
        """
        self._xor_args(idxs, ids)

        # Proposals are checked by idx, not by id so we need to find their idxs
        if ids is not None:
            idxs = [self.img_idx_lookup[img_id] for img_id in ids]

        selector = self.proposals.img_idx.isin(idxs)
        return self.proposals[selector]

    def calculate_metrics(self, iou_thrs=(0.5, 0.55), classwise=False,
                          average_thrs=True):
        """Calculates proposed bounding box validation metrics.

        Calculates accuracy as total true positives / total detections
        Calculates the AP with IoU = .50. Will return a mean AP as well
        as a class-wise AP.
        Calculates the AR with 100 detections per image.

        :param list iou_thrs: IOU threshold range to calculate. Two values
            should be given. IOU is then calculated for each threshold value in
            the given range.
        :param bool classwise: Whether or not to use calculate classwise-
            metrics. If False, uses calculates average metrics.
        :param bool average_thrs: Whether or not to get the average of the
            thresholds range.

        :returns A dictionary of calculated metric values.
        :rtype: dict
        """

        def calculate_tpfp(detection, img_gt):
            """Calculates whether a detection is a true or false positive.

            :param pd.Series detection: Data frame for the detection
            :param pd.DataFrame img_gt: Ground truth for the image.
            :returns: ann_id as int of true positive bbox. If the detection is a
                false positive, then returns -1. Also returns the overlap as a
                float with the true positive bbox. Keys are 'bbox'_id' and
                'overlap'.
            :rtype: dict
            """

            def calculate_oriented_overlap(row):
                return iou_poly(VectorDouble(row['gt']),
                                VectorDouble(row['det']))

            def calculate_aligned_overlap(row):
                # row = row[1]
                a = row['gt']
                b = row['det']
                dx_int = min([a[2], b[2]]) - max([a[0], b[0]])
                dy_int = min([a[3], b[3]]) - max([a[1], b[1]])

                dx_ov = max([a[2], b[2]]) - min([a[0], b[0]])
                dy_ov = max([a[3], b[3]]) - min([a[1], b[1]])

                if (dx_int >= 0) and (dy_int >= 0):
                    return (dx_int * dy_int) / (dx_ov * dy_ov)
                else:
                    return 0.

            # expect to only have one annotation set at this point
            gt_cat_id = img_gt['cat_id'].map(lambda x: x[0])
            same_cat_gt = img_gt[gt_cat_id == detection['cat_id']]
            if len(same_cat_gt) > 0:
                if self.props_oriented:
                    df = pd.DataFrame({
                        'gt': same_cat_gt['o_bbox'],
                        'det': [detection['bbox'] * len(same_cat_gt)]
                    })
                    overlaps = df.apply(calculate_oriented_overlap, 1)
                else:
                    df = pd.DataFrame({
                        'gt': same_cat_gt['a_bbox'],
                        'det': [detection['bbox']] * len(same_cat_gt)
                    })
                    # overlaps = np.zeros(df.shape[0])
                    # for id, row in enumerate(df.iterrows()):
                    #     calculate_aligned_overlap(row)
                    #     print(row)
                    overlaps = df.apply(calculate_aligned_overlap, 1)

                max_overlap = overlaps.max()

                # Means that there's at least one with an overlap. We take the
                # object with highest overlap.
                return {'bbox_id': overlaps.idxmax(), 'overlap': max_overlap}

            else:
                return {'bbox_id': -1, 'overlap': 0.}

        overlaps = []
        unique_images = np.unique(self.proposals['img_idx'])
        tot_props = self.proposals['cat_id'].value_counts()
        for img_idx in tqdm(unique_images):
            # For every image, look at each detection
            # img_props is a pandas DataFrame
            img_props = self.proposals[self.proposals['img_idx'] == img_idx]
            img_gt = self.get_anns(img_idx=img_idx)  # This is a dict of dicts

            # For all detections in an image, compare them to the ground truths
            for det_idx, det in img_props.iterrows():
                tpfp = calculate_tpfp(det, img_gt)
                val, overlap = tpfp['bbox_id'], tpfp['overlap']
                overlaps.append([val, overlap, det['cat_id']])

        overlaps = np.array(overlaps)
        # if overlaps_savefile is not None:
        #     with open(overlaps_savefile+'.npy', 'wb') as f:
        #         np.save(f, overlaps)
        # overlaps = np.load("overlaps.npy")

        results_dict = {}
        if classwise:
            for class_idx in np.unique(overlaps[:, 2]):
                results_dict[class_idx] = self._evaluate_overlaps(
                    overlaps[overlaps[:, 2] == class_idx],
                    tot_props,
                    iou_thrs,
                    by_class=class_idx
                )
        else:
            results_dict["average"] = self._evaluate_overlaps(
                overlaps,
                tot_props,
                iou_thrs)

        if average_thrs:
            for cls_key, tresh_dict in results_dict.items():
                averaged_dict = {'accuracy': 0,
                                 'precision': 0,
                                 'recall': 0}
                for _, eval_dict in tresh_dict.items():
                    for key in averaged_dict.keys():
                        averaged_dict[key] += eval_dict[key]
                for key in averaged_dict.keys():
                    averaged_dict[key] = averaged_dict[key] / len(tresh_dict)
                results_dict[cls_key] = averaged_dict
        return results_dict

    def _evaluate_overlaps(self, overlaps, tot_props, iou_thrs, by_class=None):
        overlaps_dict = {}
        for iou_thr in iou_thrs:

            tp = overlaps[overlaps[:, 1] >= iou_thr]
            fp = overlaps[overlaps[:, 1] < iou_thr]

            # Count number of False Positive (i.e. calculate_tpfp returned -1)
            tot_fp = len(fp)

            # Count number of ground truths with a corresponding detection
            # (True Positive)
            unique_indexes = np.unique(tp[:, 0], return_index=True)[1]
            tp_set = tp[unique_indexes]
            tot_tp = len(tp_set)

            # Count number of ground truths with multiple corresponding
            # detections (False Positive)
            tot_fp += len(tp) - len(tp_set)

            # Count number of ground truths without a corresponding detection
            # (False Negative)
            if by_class is not None:
                ann_gt_idxs = list(
                    self.ann_info[self.ann_info['cat_id'].map(
                        lambda x: int(x[0])) == by_class].index
                )
            else:
                ann_gt_idxs = list(self.ann_info.index)
            fn = []
            for i in list(tp_set[:, 0]):
                if i not in ann_gt_idxs:
                    fn.append(i)
            if by_class is not None:
                accuracy = tot_tp / tot_props[by_class]
            else:
                accuracy = tot_tp / tot_props.sum()

            precision = tot_tp / (tot_tp + tot_fp)
            if tot_tp == 0:  # avoid division by zero
                recall = 0
            else:
                recall = tot_tp / (tot_tp + len(fn))

            overlaps_dict[iou_thr] = {'accuracy': accuracy,
                                      'precision': precision,
                                      'recall': recall}
        return overlaps_dict

    def _draw_bbox(self, draw, ann, color, oriented, annotation_set=None):
        """Draws the bounding box onto an image with a given color.

        :param ImageDraw.ImageDraw draw: ImageDraw object to draw with.
        :param dict ann: Annotation information dictionary of the current
            bounding box to draw.
        :param str color: Color to draw the bounding box in as a hex string,
            e.g. '#00ff00'
        :param bool oriented: Choose between drawing oriented or aligned
            bounding box.
        :param Optional[int] annotation_set: Index of the annotation set to be
            drawn. If None is given, the first one available will be drawn.
        :return: The drawn object.
        :rtype: ImageDraw.ImageDraw
        """
        annotation_set = 0 if annotation_set is None else annotation_set
        cat_id = ann['cat_id']
        if isinstance(cat_id, list):
            cat_id = int(cat_id[annotation_set])
        cat = self.cat_info[cat_id]['name']
        if oriented:
            bbox = ann['o_bbox']
            draw.polygon(bbox, outline=color)
        else:
            bbox = ann['a_bbox']
            draw.rectangle(bbox, outline=color)

        # Now draw the label below the bbox
        x0 = min(bbox[::2])
        y0 = max(bbox[1::2])

        x1, y1 = ImageFont.load_default().getsize(cat)
        x1 += x0 + 4
        y1 += y0 + 4
        draw.rectangle((x0, y0, x1, y1), fill='#303030')
        draw.text((x0 + 2, y0 + 2), cat, '#ffffff')
        return draw

    def visualize(self,
                  img_idx=None,
                  img_id=None,
                  data_root=None,
                  out_dir=None,
                  annotation_set=None,
                  oriented=True,
                  show=True):
        """Uses PIL to visualize the ground truth labels of a given image.

        img_idx and img_id are mutually exclusive. Only one can be used at a
        time. If proposals are currently loaded, then also visualizes the
        proposals.

        :param int img_idx: The index of the desired image.
        :param int img_id: The id of the desired image.
        :param Optional[str] data_root: Path to the root data directory. If
            none is given, it is assumed to be the parent directory of the
            ann_file path.
        :param Optional[str] out_dir: Directory to save the visualizations in.
            If a directory is given, then the visualizations produced will also
            be saved.
        :param Optional[str] annotation_set: The annotation set to be
            visualized. If None is given, then the first annotation set
            available will be visualized.
        :param Optional[bool] oriented: Whether to show aligned or oriented
            bounding boxes. A value of True means it will show oriented boxes.
        :param bool show: Whether or not to use pillow's show() method to
            visualize the image.
        """
        # Since we can only visualize a single image at a time, we do i[0] so
        # that we don't have to deal with lists. get_img_ann_pair() returns a
        # tuple that's why we use list comprehension
        img_idx = [img_idx] if img_idx is not None else None
        img_id = [img_id] if img_id is not None else None

        if annotation_set is None:
            annotation_set = 0
        else:
            annotation_set = self.annotation_sets.index(annotation_set)

        img_info, ann_info = [i[0] for i in
                              self.get_img_ann_pair(
                                  idxs=img_idx, ids=img_id,
                                  ann_set_filter=annotation_set)]

        # Get the data_root from the ann_file path if it doesn't exist
        if data_root is None:
            data_root = osp.split(self.ann_file)[0]

        img_dir = osp.join(data_root, 'images')
        seg_dir = osp.join(data_root, 'segmentation')

        # Get the actual image filepath and the segmentation filepath
        img_fp = osp.join(img_dir, img_info['filename'])
        print(f'Visualizing {img_fp}...')

        # Remember: PIL Images are in form (h, w, 3)
        img = Image.open(img_fp)

        seg_fp = osp.join(
            seg_dir,
            osp.splitext(img_info['filename'])[0] + '_seg.png'
        )
        seg = Image.open(seg_fp)

        # Here we overlay the segmentation on the original image using the
        # colorcet colors
        # First we need to get the new color values from colorcet
        colors = [ImageColor.getrgb(i) for i in cc.glasbey]
        colors = np.array(colors).reshape(768, ).tolist()
        colors[0:3] = [0, 0, 0]  # Set background to black

        # Then put the palette
        seg.putpalette(colors)

        # Now the img and the segmentation can be composed together. Black
        # areas in the segmentation (i.e. background) are ignored
        seg_array = np.array(seg)
        mask = np.zeros_like(seg_array)
        mask[np.where(seg_array == 0)] = 255
        mask = Image.fromarray(mask, mode='L')

        img = Image.composite(img, seg.convert('RGB'), mask)
        draw = ImageDraw.Draw(img)

        # Now draw the gt bounding boxes onto the image
        for ann in ann_info.to_dict('records'):
            draw = self._draw_bbox(draw, ann, '#00ff00', oriented,
                                   annotation_set)

        if self.proposals is not None:
            prop_info = self.get_img_props(idxs=img_idx, ids=img_id)

            for prop in prop_info.to_dict('records'):
                prop_oriented = len(prop['bbox']) == 8
                draw = self._draw_bbox(draw, prop, '#ff0000', prop_oriented)

        if show:
            img.show()
        if out_dir is not None:
            img.save(osp.join(out_dir, datetime.now().strftime('%m-%d_%H%M%S'))
                     + '.png')
